site_name: FSA MkDocs Theme
repo_name: FSA_mkdocs_theme
repo_url: https://github.com/FoodStandardsAgency/FSA_mkdocs_theme
docs_dir: docs

theme:
  name: material
  custom_dir: ons_mkdocs_theme
  palette:
    primary: custom
    accent: custom
  font:
    text: Open Sans
    code: Roboto Mono
  features:
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  language: en
  logo: assets/images/fsa-logo.svg
  favicon: assets/images/favicon.ico

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://fonts.googleapis.com/css2?family=Fira+Sans:wght@700&family=Open+Sans:wght@400;600&display=swap

nav:
  - Home: index.md
  - Setup: setup.md
  - Creating your site: creating-your-site.md
  - Building your site: building-your-site.md
  - Customisation: customisation.md
  - Design Standards: design-standards.md
  - Contributing:
    - Reporting a bug: contributing/reporting-a-bug.md
    - Reporting a docs issue: contributing/reporting-a-docs-issue.md

plugins:
  - search:
      enabled: true
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FoodStandardsAgency/FSA_mkdocs_theme

copyright: |
  &copy; <a href="https://www.food.gov.uk">Food Standards Agency 2026</a>

watch:
  - docs/
  - ons_mkdocs_theme/